// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/fe47fd39e0e5b679954fb9fa9063ce5f08c49522/gulp-install/gulp-install.d.ts
declare module "gulp-install" {
  interface Options {
    production?: boolean;
    ignoreScripts?: boolean;
    noOptional?: boolean;
    allowRoot?: boolean;
    args?: string | string[];
  }

  interface Install {
    (options?: Options) : NodeJS.ReadWriteStream;
  }

  const install : Install;
  export = install;
}
